server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pmsdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your_super_secret_key_which_is_long_enough_to_be_secure_and_is_not_guessable
  expiration_time: 86400000 # 24 hours
