server:
  port: 8082

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pmsdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true