server:
  port: 8083

spring:
  application:
    name: document-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pmsdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# AWS S3 configuration (example)
aws:
  s3:
    bucket-name: your-s3-bucket-name
    region: your-aws-region