server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE # Eureka/Consul 같은 Service Discovery 사용을 가정
          # uri: http://localhost:8081 # 로컬 테스트 시
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: project-service
          uri: lb://PROJECT-SERVICE
          # uri: http://localhost:8082
          predicates:
            - Path=/project-service/**
          filters:
            - RewritePath=/project-service/(?<segment>.*), /$\{segment}
        - id: document-service
          uri: lb://DOCUMENT-SERVICE
          # uri: http://localhost:8083
          predicates:
            - Path=/document-service/**
          filters:
            - RewritePath=/document-service/(?<segment>.*), /$\{segment}

# Custom properties for JWT
jwt:
  secret: your_super_secret_key_which_is_long_enough_to_be_secure_and_is_not_guessable
